### ISSUE TITLE
"Batteries included" vs. "do one thing well"

### ISSUE THREAD

**Issue by schurzi** [T-Systems-MMS/cmcc-operator#1]
great work so far @stefanbethke!

I have taken a look at this operator for our projects and I'm wondering if you try to solve too much in one operator. Especially the MariaDB/MongoDB and in part the Solr components are standing out to me. For these components we could use different operators, that specialize in the dedicated software.

From a quick check, there are already comprehensive existing solutions in existence:

- for MySQL/MongoDB https://www.percona.com/software/percona-kubernetes-operators
- for Solr https://solr.apache.org/operator/

My opinion:

- keeping all in one operator is beneficial for dev environments
- in any other environment (prod, cloud) we would use other means of provisioning databases, since we also need configuration
- especially exposing detail configuration for MySQL/MongoDB/Solr will add a lot of options
- keeping the operator small helps in maintaining it better

With this in mind I would drift toward removing the additional components, that can be managed by a different operator. This would add a few more steps to the dev setup, but it would be more in line with all other use-cases.

What do you think about splitting responsibilities into different operators?

**Comment by stefanbethke** [comment]
The MongoDB and MariaDB components are strictly optional, and are meant for development environments, only. I have no intention of extending it to production-like setups.

Solr, on the other hand, is a somewhat customized CoreMedia image. I'm happy to look into making the Solr setup external explicitly, but right now you can already disable Solr by setting
```
- components:
  - type: solr
    milestone: Never
```

and add it separately. It's relatively easy for me to make the Solr connection completely customizable, similar to the UAPI or database connections.

We're going to use Azure database services for the test and prod envs soon.

**Comment by schurzi** [comment]
Defining Solr as part of the CoreMedia components is fine for me. I am also unsure if it would be beneficial to externalize the Solr stack.

I have mixed feelings about the remaining DB options. Currently we don't have many different users and I think with all the distributions for MySQL (MariaDB, Percona, Oracle), MongoDB and all the configuration possibilities of these DB servers there will be some need for passing configuration options through our operator. At some point we will start to add project specific DB configurations for a development environment. I think this point will come rather sooner than later. And I also think this is a bad problem to solve in a generic way. That is why I believe the DB should not be a part of the operator, not even for development purposes.

I am sure that this feature can easily be replaced by using another operator or a simple deployment with an user supplied k8s manifest.

Since this feature currently exists and is beneficial, I would advocate for deprecating it before it starts growing and instead add documentation and examples describing another way of handling things.

**Comment by stefanbethke** [comment]
There is no need to enable `with.databases`. You can leave that off, and supply the necessary database connection information, see https://github.com/T-Systems-MMS/cmcc-operator/blob/main/docs/custom-resource.md#using-pre-existing-secrets

if you have suggestions on improving the documentation to better explain these scenarios, I would be grateful.

**Comment by stefanbethke** [comment]
Do you have further comments or suggestions? Otherwise, I would close this issue.

**Comment by schurzi** [comment]
Thanks for discussing this. At the moment I have no other comments in this regard. So keeping this open will serve no purpose.
