### ISSUE TITLE
initial solr replication fails -> no solr cores on follower instances

### ISSUE THREAD

**Issue by hegessne** [T-Systems-MMS/cmcc-operator#59]
when establishing solr follower instances the solr cores must be created because the replication otherwise will fail.

our workaround was to create them manually connecting each follower pod
`curl 'http://127.0.0.1:8983/solr/admin/cores?action=CREATE&name=studio&configSet=content&dataDir=data'`
`curl 'http://127.0.0.1:8983/solr/admin/cores?action=CREATE&name=preview&configSet=cae&dataDir=data'`
`curl 'http://127.0.0.1:8983/solr/admin/cores?action=CREATE&name=live&configSet=cae&dataDir=data'`

**Comment by stefanbethke** [comment]
The intention in the operator was to use secrets to configure the Solr clients and their connection to the Solr servers (leader or followers); however, that has not been implemented fully. Instead, the Solr client configuration is injected directly as environment variables.
