### ISSUE TITLE
UAPI Blob Cache should be an emptyDir

### ISSUE THREAD

**Issue by stefanbethke** [T-Systems-MMS/cmcc-operator#74]
**Is your feature request related to a problem? Please describe.**
Right now, the UAPI blob cache is configured as a PVC. However, the UAPI cache will be cleaned/deleted on startup of the client, and it therefor unnecessary to use a PVC for that.

**Describe the solution you'd like**
Use an emptyDir for the blob cache, and make sure the disk space health check is configured correctly, so the component is restarted if the emptyDir grows too big.

**Comment by stefanbethke** [comment]
Changing this has to be evaluated properly:
* EmptyDirs canot be limited in size; this might lead to problems if the caches grow too big. With a PVC, the total amount is limited.
* Depending on the k8s platform, EmptyDirs might incur additional cost or resource limitations compared to PVCs.
* EmptyDirs might have different performance characteristics to PVCS.

**Comment by schurzi** [comment]
you could also use ephemeral Volumes: https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes

**Comment by stefanbethke** [comment]
This has been superceded by #103.
