### ISSUE TITLE
hardcoded container registries (docker.io) should be configurable

### ISSUE THREAD

**Issue by hegessne** [T-Systems-MMS/cmcc-operator#75]
# intro
We need to configure trusted registries to comply security requirements.

# requirement
focussed on security the container registry "docker.io" is not trusted for us.
so the registry should be configurable (openjdk, alpine/curl, mariadb, mongo, nginx; https://github.com/T-Systems-MMS/cmcc-operator/search?q=docker.io) in custom resource definition (like other images).

**Comment by stefanbethke** [comment]
Implemented in e38daa590abed18259f4b901641e95fe770bd86e
